# -*- coding: utf-8 -*-
"""chatbotAcademico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_LSCGBv6UVZD7mEqUsuYhKyGadrFmr0
"""

import unicodedata
import re

ARQUIVO = "FATEB_reorganizado.txt"

def normalizar(texto):
    texto = texto.lower()
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(c for c in texto if unicodedata.category(c) != "Mn")
    texto = re.sub(r"[^\w\s]", " ", texto)
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto

def carregar_base(nome_arquivo):
    with open(nome_arquivo, "r", encoding="utf-8") as f:
        conteudo = f.read()

    secoes = conteudo.split("[CURSO]")
    parte_geral = secoes[0]
    cursos_brutos = secoes[1:]

    geral = {}
    cursos = []

    for linha in parte_geral.splitlines():
        linha = linha.strip()
        if not linha or linha == "[GERAL]":
            continue
        if ":" in linha:
            chave, valor = linha.split(":", 1)
            geral[normalizar(chave)] = valor.strip()

    for bloco in cursos_brutos:
        curso = {}
        for linha in bloco.splitlines():
            linha = linha.strip()
            if not linha:
                continue
            if ":" in linha:
                chave, valor = linha.split(":", 1)
                curso[normalizar(chave)] = valor.strip()
        if curso:
            cursos.append(curso)

    return geral, cursos

geral, cursos = carregar_base(ARQUIVO)

def listar_cursos():
    nomes = [curso.get("nome", "Curso sem nome") for curso in cursos]
    return "Cursos disponíveis:\n- " + "\n- ".join(nomes)

def encontrar_curso_na_pergunta(pergunta_norm):
    for curso in cursos:
        nome = curso.get("nome", "")
        if normalizar(nome) in pergunta_norm:
            return curso
    return None

def responder(pergunta):
    pergunta_norm = normalizar(pergunta)

    if "curso" in pergunta_norm and ("quais" in pergunta_norm or "lista" in pergunta_norm or "tem" in pergunta_norm or "oferece" in pergunta_norm):
        return listar_cursos()

    if "endereco" in pergunta_norm:
        return geral.get("endereco", "Endereço não encontrado.")
    if "fone" in pergunta_norm or "telefone" in pergunta_norm or "whatsapp" in pergunta_norm or "contato" in pergunta_norm:
        return geral.get("fone", "Telefone não encontrado.")
    if "email" in pergunta_norm or "e mail" in pergunta_norm:
        return geral.get("email", "E-mail não encontrado.")
    if "site" in pergunta_norm:
        return geral.get("site", "Site não encontrado.")
    if "missao" in pergunta_norm:
        return geral.get("missao", "Missão não encontrada.")
    if "visao" in pergunta_norm:
        return geral.get("visao", "Visão não encontrada.")
    if "valor" in pergunta_norm or "valores" in pergunta_norm:
        return geral.get("valores", "Valores não encontrados.")

    curso = encontrar_curso_na_pergunta(pergunta_norm)
    if curso:
        if "coorden" in pergunta_norm:
            return curso.get("coordenacao", "Coordenação não encontrada.")
        if "professor" in pergunta_norm or "docente" in pergunta_norm:
            return curso.get("professores", "Professores não encontrados.")
        if "objetivo" in pergunta_norm:
            return curso.get("objetivo", "Objetivo não encontrado.")
        if "perfil" in pergunta_norm:
            return curso.get("perfil", "Perfil não encontrado.")
        if "mercado" in pergunta_norm or "trabalho" in pergunta_norm:
            return curso.get("mercado", "Mercado de trabalho não encontrado.")
        return (
            f"Curso: {curso.get('nome', 'Não identificado')}\n"
            f"Objetivo: {curso.get('objetivo', 'Não encontrado.')}\n"
            f"Coordenação: {curso.get('coordenacao', 'Não encontrada.')}"
        )

    return (
        "Não entendi muito bem. Tente perguntas como:\n"
        "- Quais cursos a FATEB oferece?\n"
        "- Qual é o endereço da FATEB?\n"
        "- Quem é o coordenador de Engenharia de Software?\n"
        "- Quais são os professores de Direito?"
    )

while True:
    pergunta = input("Você: ")
    if normalizar(pergunta) == "sair":
        print("Chatbot: Até logo!")
        break

    resposta = responder(pergunta)
    print("Chatbot:", resposta)