# -*- coding: utf-8 -*-
"""chatbotAcademico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_LSCGBv6UVZD7mEqUsuYhKyGadrFmr0
"""

import unicodedata
import re

ARQUIVO = "fateb_estruturado.txt"

def normalizar(texto):
    texto = texto.lower()
    texto = unicodedata.normalize("NFD", texto)
    texto = "".join(c for c in texto if unicodedata.category(c) != "Mn")
    texto = re.sub(r"[^\w\s]", " ", texto)
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto

def carregar_base(arquivo):
    with open(arquivo, "r", encoding="utf-8") as f:
        conteudo = f.read()

    secoes = conteudo.split("[CURSO]")
    parte_geral = secoes[0]
    cursos_brutos = secoes[1:]

    geral = {}
    cursos = []

    for linha in parte_geral.splitlines():
        linha = linha.strip()
        if not linha or linha == "[INSTITUICAO]":
            continue
        if "=" in linha:
            chave, valor = linha.split("=", 1)
            geral[normalizar(chave)] = valor.strip()

    for bloco in cursos_brutos:
        curso = {}
        for linha in bloco.splitlines():
            linha = linha.strip()
            if not linha:
                continue
            if "=" in linha:
                chave, valor = linha.split("=", 1)
                curso[normalizar(chave)] = valor.strip()
        if curso:
            cursos.append(curso)

    return geral, cursos

geral, cursos = carregar_base(ARQUIVO)


def listar_cursos():
    nomes = [curso.get("nome", "Curso sem nome") for curso in cursos]
    return "Cursos disponíveis:\n- " + "\n- ".join(nomes)

def encontrar_curso_na_pergunta(pergunta_norm):
    for curso in cursos:
        nome = curso.get("nome", "")
        if normalizar(nome) in pergunta_norm:
            return curso
    return None

def listar_disciplinas(curso):
    disciplinas_por_periodo = []

    for chave, valor in curso.items():
        if re.match(r"^\d+a?$", normalizar(chave).replace("ª", "a")):
            disciplinas_por_periodo.append((chave, valor))

    disciplinas_por_periodo = []
    for chave, valor in curso.items():
        if re.match(r"^\d+ª$", chave):
            disciplinas_por_periodo.append((chave, valor))

    if not disciplinas_por_periodo:
        return "Disciplinas não encontradas."

    def chave_ordenacao(item):
        numero = re.findall(r"\d+", item[0])
        return int(numero[0]) if numero else 999

    disciplinas_por_periodo.sort(key=chave_ordenacao)

    resposta = []
    for periodo, disciplinas in disciplinas_por_periodo:
        lista = [d.strip() for d in disciplinas.split("|")]
        resposta.append(f"{periodo} bimestre:")
        for disciplina in lista:
            resposta.append(f"- {disciplina}")
        carga = curso.get(f"{periodo}_carga_horaria_total")
        if carga:
            resposta.append(f"Carga horária do {periodo} bimestre: {carga}")
        resposta.append("")

    return "\n".join(resposta).strip()

def responder(pergunta):
    pergunta_norm = normalizar(pergunta)

    if "curso" in pergunta_norm and (
        "quais" in pergunta_norm
        or "lista" in pergunta_norm
        or "tem" in pergunta_norm
        or "oferece" in pergunta_norm
    ):
        return listar_cursos()

    if "endereco" in pergunta_norm:
        return geral.get("endereco", "Endereço não encontrado.")
    if "fone" in pergunta_norm or "telefone" in pergunta_norm or "whatsapp" in pergunta_norm or "contato" in pergunta_norm:
        return geral.get("telefones", "Telefones não encontrados.")
    if "email" in pergunta_norm or "e mail" in pergunta_norm:
        return geral.get("emails", "E-mails não encontrados.")
    if "site" in pergunta_norm:
        return geral.get("site", "Site não encontrado.")
    if "missao" in pergunta_norm:
        return geral.get("missao", "Missão não encontrada.")
    if "visao" in pergunta_norm:
        return geral.get("visao", "Visão não encontrada.")
    if "valor" in pergunta_norm or "valores" in pergunta_norm:
        return geral.get("valores", "Valores não encontrados.")
    if "fundada" in pergunta_norm or "fundacao" in pergunta_norm or "inaugural" in pergunta_norm:
        return geral.get("aula_inaugural", "Data de fundação/início não encontrada.")
    if "instituicao" in pergunta_norm and ("o que e" in pergunta_norm or "sobre" in pergunta_norm):
        return geral.get("descricao", "Descrição da instituição não encontrada.")

    curso = encontrar_curso_na_pergunta(pergunta_norm)
    if curso:
        if "coorden" in pergunta_norm:
            return curso.get("coordenacao", "Coordenação não encontrada.")

        if "professor" in pergunta_norm or "docente" in pergunta_norm:
            return curso.get("professores", "Professores não encontrados.")

        if "objetivo" in pergunta_norm:
            return curso.get("objetivo", "Objetivo não encontrado.")

        if "perfil" in pergunta_norm:
            return curso.get("perfil_profissional", "Perfil profissional não encontrado.")

        if "mercado" in pergunta_norm or "trabalho" in pergunta_norm:
            return curso.get("mercado_de_trabalho", "Mercado de trabalho não encontrado.")

        if "duracao" in pergunta_norm or "quanto tempo" in pergunta_norm:
            bimestres = curso.get("duracao_bimestres", "Não encontrado")
            anos = curso.get("duracao_anos_aproximados", "Não encontrado")
            return f"Duração do curso de {curso.get('nome', '')}: {bimestres} bimestres ({anos} anos aproximados)."

        if "carga horaria" in pergunta_norm:
            return f"Carga horária total do curso de {curso.get('nome', '')}: {curso.get('carga_horaria_total', 'Não encontrada.')}"

        if "disciplina" in pergunta_norm or "grade" in pergunta_norm or "materia" in pergunta_norm:
            return listar_disciplinas(curso)

        return (
            f"Curso: {curso.get('nome', 'Não identificado')}\n"
            f"Duração: {curso.get('duracao_bimestres', 'Não encontrada')} bimestres\n"
            f"Coordenação: {curso.get('coordenacao', 'Não encontrada.')}\n"
            f"Objetivo: {curso.get('objetivo', 'Não encontrado.')}"
        )

    return (
        "Não entendi muito bem. Tente perguntas como:\n"
        "- Quais cursos a FATEB oferece?\n"
        "- Qual é o endereço da FATEB?\n"
        "- Quem é o coordenador de Engenharia de Software?\n"
        "- Quais são os professores de Direito?\n"
        "- Qual a duração de Administração?\n"
        "- Quais são as disciplinas de Pedagogia?"
    )

while True:
    pergunta = input("Você: ")

    if normalizar(pergunta) == "sair":
        print("Chatbot: Até logo!")
        break

    resposta = responder(pergunta)
    print("Chatbot:", resposta)